/** Analyst proposals derived from the linked company cases, not verified Bangladesh outcomes. */
export type DecisionStage = "Pilot first" | "Conditional next" | "Later" | "JCX parallel" | "Avoid at launch";
export interface CompanyDecision {
  features: string[];
  payer: string;
  local: string;
  stage: DecisionStage;
}

export const companyDecisions: Record<string, CompanyDecision> = {
  beike: { features: ["Agent role records", "Commission allocation"], payer: "Closing commissions and platform services", local: "Start with a small partner group and written lead, role and fee rules. Do not assume a nationwide network.", stage: "Pilot first" },
  compass: { features: ["Agent workflow tools", "Closing coordination"], payer: "Commission when a transaction closes", local: "Name the responsible local operator. Count agent payments and failed-deal effort in every sale.", stage: "Pilot first" },
  quintoandar: { features: ["Rental contracts", "Collections and management"], payer: "Brokerage and administration fees", local: "Test landlord demand and monthly service cost first. Do not copy rent guarantees before understanding losses and responsibility.", stage: "Conditional next" },
  nobroker: { features: ["Assisted shortlisting", "Viewing appointments"], payer: "Customers buying assistance plans", local: "Test phone-assisted search in Bangla and English. Define what staff will do; appointment booking is not an accompanied visit.", stage: "Pilot first" },
  "square-yards": { features: ["Developer lead registration", "Booking and payout tracking"], payer: "Developer commissions and related services", local: "Use one authorised project and record collected commission, not just reservations. Disclose JCX's ownership.", stage: "Pilot first" },
  proptiger: { features: ["New-home purchase support", "Separate business-line reporting"], payer: "Developer and portal revenue streams in the historical portfolio", local: "Keep Propty's external revenue separate from internal JCX referrals and costs. Historical group figures are not standalone results.", stage: "Pilot first" },
  houm: { features: ["Tenant placement", "Recurring rental administration"], payer: "Rental placement and administration fees", local: "Try a small landlord group only if there is demand. Record collection, inspection and repair effort per property.", stage: "Conditional next" },
  appfolio: { features: ["Property-manager software", "Operational records"], payer: "Subscription and usage-based fees", local: "First find managers willing to use and pay for software. A spreadsheet replacement is not automatically a business.", stage: "Conditional next" },
  "urban-company": { features: ["Home-service bookings", "Provider training and quality control"], payer: "Revenue from service transactions", local: "Add one service category with dependable providers before bundling many. Track complaints, repeat use and provider costs.", stage: "Conditional next" },
  "sheba-platform": { features: ["Local provider matching", "Service fulfilment"], payer: "Transaction and payment services; margins not established", local: "Study local provider reliability and cash collection. Do not assume app bookings alone solve delivery problems.", stage: "Conditional next" },
  costar: { features: ["Structured property research", "Professional data products"], payer: "Professional subscriptions", local: "Collect permissioned, consistently defined records first. Test one institutional payer before creating a broad data product.", stage: "Later" },
  aldar: { features: ["Customer self-service", "Digital sales workflow"], payer: "Internal developer investment, not a separate software business", local: "For JCX: offer status updates and service requests alongside staff support. Test local signing requirements separately.", stage: "JCX parallel" },
  "godrej-properties": { features: ["Complaint tracking", "Escalation ownership"], payer: "Internal developer investment", local: "Give every request an owner and deadline. Measure actual resolution time, not just closed-ticket counts.", stage: "JCX parallel" },
  "ayala-land": { features: ["Construction inspections", "Quality-control records"], payer: "Internal developer investment", local: "Choose one inspection process with site staff. Compare error and rework rates before expanding.", stage: "JCX parallel" },
  dlf: { features: ["Integrated business records", "Process controls"], payer: "Internal developer investment", local: "Map existing JCX tools and data owners first. Do not replace every system simply to launch Propty.", stage: "JCX parallel" },
  permitflow: { features: ["Approval task tracking", "Preconstruction documents"], payer: "Workflow software; detailed economics not established", local: "Map one Bangladesh approval process with local professionals. Track documents first; do not promise automated approvals.", stage: "Later" },
  snapdocs: { features: ["Shared closing status", "Document handoffs"], payer: "Professional transaction parties", local: "Borrow the checklist and named task owners. Do not assume US mortgage or electronic-closing rules apply here.", stage: "Pilot first" },
  rabbet: { features: ["Construction-finance records", "Document coordination"], payer: "Not established in the reviewed profile", local: "Check whether a lender or developer will pay to solve a repeated document problem before making a separate product.", stage: "Later" },
  trellis: { features: ["Rental task automation", "Maintenance coordination"], payer: "Not established in the reviewed profile", local: "If rentals become a real operation, automate reminders before sensitive decisions. Keep staff escalation and error records.", stage: "Later" },
  lhoopa: { features: ["Housing delivery operations", "Technology-supported property supply"], payer: "Home buyers; debt and equity finance the business", local: "Keep owned-home development separate from a light service pilot. Its capital needs cannot be treated as software costs.", stage: "Avoid at launch" },
  rightmove: { features: ["Structured property listings", "Paid advertiser visibility"], payer: "Agents and developers buying recurring packages", local: "Build usable listings first. Charge for promotion only after showing recurring demand and advertiser value.", stage: "Conditional next" },
  "99acres": { features: ["Property discovery", "Advertiser products"], payer: "Property advertisers", local: "Test an actual paying advertiser and completed customer journeys before scaling traffic or paid listing packages.", stage: "Conditional next" },
  pinhome: { features: ["Connected property journey", "Financing and service adjacencies"], payer: "Multiple parties; segment economics not established", local: "Use the integrated journey as a long-term direction. Add services one at a time after the initial journey works.", stage: "Conditional next" },
  propzy: { features: ["Offline transaction assistance", "Online property discovery"], payer: "Historical transaction-service model", local: "Learn from its closure: cap fixed costs and service scope. Do not launch a large office network before viable delivery economics.", stage: "Avoid at launch" },
  bayut: { features: ["Dated availability checks", "Defined verification badges"], payer: "Payer economics not established by the selected product source", local: "Show what was checked, by whom and when. A listing check must not be presented as a legal ownership guarantee.", stage: "Pilot first" },
  landeed: { features: ["Property-record access", "Document evidence trails"], payer: "Terms not established in the selected profile", local: "Start with a document checklist and permissioned records. Get qualified local review before selling legal verification.", stage: "Later" },
  propexo: { features: ["Software integrations", "Connected property systems"], payer: "Terms not established in the selected profile", local: "Integrate only if JCX already has useful systems, lawful access and repeated double entry worth removing.", stage: "JCX parallel" },
};

export const proptyFeatures = [
  { name: "Listings people can check", build: "Accurate details, permission to market, latest availability check and clear limits.", companies: ["bayut", "beike"], stage: "Pilot first", measure: "Stale or incorrect listings; time spent checking each one." },
  { name: "Help finding and visiting a home", build: "Budget and location intake, a shortlist, a named adviser and visit scheduling.", companies: ["nobroker", "square-yards"], stage: "Pilot first", measure: "Response time, suitable visits and customer drop-off." },
  { name: "A shared transaction checklist", build: "Next step, responsible person, document status and a record of delays.", companies: ["snapdocs", "beike"], stage: "Pilot first", measure: "Missed handoffs, delays and reasons deals stop." },
  { name: "Clear partner roles and payments", build: "Lead ownership, agreed fee event, agent split and collected-payment record.", companies: ["beike", "square-yards"], stage: "Pilot first", measure: "Fee disputes and money collected after delivery costs." },
  { name: "Rental and home services", build: "Choose tenant placement OR monthly management first. Add repairs only with dependable delivery.", companies: ["quintoandar", "houm", "urban-company", "sheba-platform"], stage: "Conditional next", measure: "Paying repeat customers, service cost, arrears and complaints." },
  { name: "A wider property marketplace", build: "Add external developers and agents, transparent ranking and paid products when they create value.", companies: ["rightmove", "99acres", "pinhome"], stage: "Conditional next", measure: "External supply, repeat advertiser payment and real customer outcomes." },
  { name: "Property data and automation", build: "Keep useful records from day one. Sell data or automate specialist tasks only after access, quality and demand are proven.", companies: ["landeed", "costar", "permitflow", "trellis"], stage: "Later", measure: "Record accuracy, lawful access, paying users and automation errors." },
] as const;

export const proptyRoadmap = [
  { time: "Weeks 0–2", title: "Choose the customer and check the starting point", action: "Interview buyers, owners and agents. Inspect available inventory, lead records, delivery costs and authority to market. Choose one segment and one small area.", gate: "Only proceed with usable supply, a named operator and an agreed payer hypothesis. If a sales pilot has no access, compare a narrow rental service instead." },
  { time: "Weeks 3–6", title: "Run the smallest complete service", action: "Test the four first features with a small operating team. Use a simple mobile website, phone support and existing tools where possible; do not build a super-app.", gate: "Check listing quality, response time, visits, staff effort and complaints against the starting point. Agree success thresholds before running the test." },
  { time: "Weeks 7–12", title: "Check whether the service creates value", action: "Follow comparable leads through to outcomes. Record fees actually collected, acquisition costs, staff time, partner payments and refunds. Separate JCX referrals from external demand.", gate: "Scale, revise or stop. If sales have not closed, extend observation instead of treating bookings as revenue or claiming proven profit." },
  { time: "After the pilot", title: "Choose one expansion, not all of them", action: "Use the evidence to choose more projects, rental administration or one home service. Build paid marketplace or data products only when their own customers and economics are established.", gate: "Each new service needs its own payer, delivery owner, cost record and stop rule. There is no automatic launch date." },
] as const;
