// Offering and batch verified against each official YC profile on 12 September 2026.
// Transfer lessons and test gates are our analysis, not claims made by YC.
export const ycShortlist = [
  { name: "Houm", batch: "Winter 2021", place: "Chile / Latin America", category: "Rentals & management", offering: "Helps landlords find tenants, collect rent and manage their properties.", lesson: "A property relationship can continue after finding the tenant.", test: "Interview landlords, price the service and record the actual cost of collections, repairs and support before offering a bundle.", limit: "This profile does not establish profitable unit economics or demand for the same bundle in Bangladesh.", url: "https://www.ycombinator.com/companies/houm" },
  { name: "Landeed", batch: "Summer 2022", place: "India", category: "Property records & checks", offering: "Structures fragmented property records for search, verification and transaction workflows.", lesson: "Make the source record accessible, not just the answer or a trust badge.", test: "Identify lawful access to local records, the checking process and who is responsible for interpreting them.", limit: "India’s record systems and coverage do not transfer automatically to Bangladesh. A software result is not a legal ownership guarantee.", url: "https://www.ycombinator.com/companies/landeed" },
  { name: "Snapdocs", batch: "Winter 2014", place: "United States", category: "Transaction coordination", offering: "Connects the parties involved in mortgage closings through digital workflow tools.", lesson: "Coordinating handoffs may be more valuable than adding another search screen.", test: "Map a real transaction, name each responsible party and test whether shared status reduces missed steps.", limit: "A US mortgage-closing workflow cannot be copied without checking local process and legal requirements.", url: "https://www.ycombinator.com/companies/snapdocs" },
  { name: "Propexo", batch: "Winter 2023", place: "United States", category: "Software integration", offering: "Provides integrations that connect commercial real-estate software and property-management systems.", lesson: "Connect useful tools instead of rebuilding every existing system.", test: "First inventory JCX’s actual tools, data quality, access rights and repeated double-entry work.", limit: "An integration business needs customers with systems worth connecting. That local demand remains unproven.", url: "https://www.ycombinator.com/companies/propexo" },
  { name: "PermitFlow", batch: "Winter 2022", place: "United States", category: "Developer operations", offering: "Provides an AI platform for contractors and developers to manage preconstruction work.", lesson: "Complex administrative work can be a focused product opportunity.", test: "Study one local approval process and test a document-and-task tracker with staff before attempting automation.", limit: "Local approval rules, access and accountability need separate research. Faster approvals are not established by this profile.", url: "https://www.ycombinator.com/companies/permitflow" },
  { name: "Trellis", batch: "Spring 2026", place: "United States", category: "Rental operations & AI", offering: "Describes AI agents coordinating short-term rental messages, cleaning, maintenance and owner updates.", lesson: "Study a complete service workflow, not a chatbot in isolation.", test: "If a rental operation is chosen, test one low-risk task with human review, a clear escalation route and an error log.", limit: "Early, company-reported claims are not audited results. Short-term hospitality is different from long-term housing. This is Trellis at trellistech.com, not a namesake.", url: "https://www.ycombinator.com/companies/trellistech" },
] as const;
